FROM centos:centos7

# Some yum install
RUN yum -y update
RUN yum install -y bc wget python mesa-libGL libquadmath file tar which gzip

# Setup Workdir
RUN mkdir /opt/fsl_install
WORKDIR   /opt/fsl_install

# Download fsl files
RUN wget https://fsl.fmrib.ox.ac.uk/fsldownloads/fslinstaller.py

# Modify order of channels in python env
RUN python fslinstaller.py  -d /usr/local/fsl

# RM src
WORKDIR /
RUN rm -rf /usr/local/fsl/src
RUN rm -rf /opt/fsl_install

# Setup FSL ENV 
ENV FSLDIR=/usr/local/fsl
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/fsl/bin
ENV LD_LIBRARY_PATH=/usr/local/fsl/lib
ENV FSLOUTPUTTYPE=NIFTI_GZ

RUN . $FSLDIR/etc/fslconf/fsl.sh


