FROM centos:centos7

# Some yum install
RUN yum -y update
RUN yum install -y bc wget python mesa-libGL libquadmath file tar which gzip

# Setup Workdir
RUN mkdir /opt/fsl_install
WORKDIR   /opt/fsl_install

# Download fsl files
RUN wget https://fsl.fmrib.ox.ac.uk/fsldownloads/fslinstaller.py 
RUN wget https://fsl.fmrib.ox.ac.uk/fsldownloads/fsl-6.0.5-centos7_64.tar.gz

#
# The installation gets stuck on stage2,
# due to some issue when fetching the SAT python package.
#
# This is documented in: 
# - https://stackoverflow.com/questions/56262012/conda-install-takes-forever-stuck-as-sat-solver
# 
# The solution is:
#   - Download the fsl-6.0.5-centos7_64.tar.gz.
#   - Extract the *.yml that defines the python env. 
#   - Switch the order of the channels (as describe on the stackoverflow solution).
#   - Replace the *.yml file by the new one in the tar file.
#   - Run the installer with the new fsl-6.0.5-centos7_64.tar.gz.
#
RUN gunzip fsl-6.0.5-centos7_64.tar.gz
RUN tar -xvf fsl-6.0.5-centos7_64.tar fsl/etc/fslconf/fslpython_environment.yml
RUN sed -i '/ - defaults/d'  fsl/etc/fslconf/fslpython_environment.yml
RUN sed -i -r 's/ - conda-forge/ - defaults\n - conda-forge/g' fsl/etc/fslconf/fslpython_environment.yml
RUN tar -uf fsl-6.0.5-centos7_64.tar fsl/etc/fslconf/fslpython_environment.yml
RUN gzip fsl-6.0.5-centos7_64.tar

# Run fslinstaller on modified *.tar.gz
RUN python fslinstaller.py -f fsl-6.0.5-centos7_64.tar.gz -M -D -d /usr/local/fsl 

# RM src
WORKDIR /
RUN rm -rf /usr/local/fsl/src
RUN rm -rf /opt/fsl_install

# Setup FSL ENV 
ENV FSLDIR=/usr/local/fsl
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/fsl/bin
ENV LD_LIBRARY_PATH=/usr/local/fsl/lib
ENV FSLOUTPUTTYPE=NIFTI_GZ

RUN . $FSLDIR/etc/fslconf/fsl.sh

